[build]
  command = "npm install"
  publish = "public"

[dev]
  command = "npm start"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

# 移除@netlify/plugin-neon插件配置，因为该版本不存在
    